In [2]:
pip install tensorflow

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 1.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.4/45.4 kB 1.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 259.7/259.7 MB 4.0 MB/s eta 0:00:0000:01m00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.7/133.7 kB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 1.0 MB/s eta 0:00:00ta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 7.2 MB/s eta 0:00:0000:010:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 8.0 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 8.2 MB/s eta 0:00:00:00:010:010m
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.5/26.5 MB 16.4 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 393.6/393.6 kB 11.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.3/20.3 MB 10.7 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 2.3 

In [4]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.16.1


In [7]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step


In [10]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [11]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.17159228, -0.0667194 ,  0.0151411 , -0.5232537 ,  0.07392789,
         0.07996085, -0.08592632,  0.1889198 ,  0.5834727 ,  0.34384397]],
      dtype=float32)

In [13]:
tf.nn.softmax(predictions).numpy()

array([[0.07746338, 0.08602846, 0.09336707, 0.05449691, 0.09902036,
        0.09961955, 0.08439188, 0.11108742, 0.1648227 , 0.12970227]],
      dtype=float32)

In [14]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [15]:
loss_fn(y_train[:1], predictions).numpy()

2.306397

In [20]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [21]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - 1ms/step - accuracy: 0.0966 - loss: 2.3710


[2.3710052967071533, 0.0966000035405159]

In [22]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [24]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.07122289, 0.07404023, 0.11985949, 0.06709994, 0.07298843,
        0.11706198, 0.11188333, 0.10803182, 0.15745877, 0.10035305],
       [0.15258344, 0.05017142, 0.08526643, 0.03033079, 0.10699373,
        0.12424907, 0.07481909, 0.0699405 , 0.20125116, 0.10439437],
       [0.09707945, 0.11916827, 0.11159057, 0.08780859, 0.09248743,
        0.12191948, 0.08847633, 0.09300017, 0.11069325, 0.07777654],
       [0.05845311, 0.09725075, 0.08219422, 0.09432145, 0.08485745,
        0.09237002, 0.07920717, 0.05373434, 0.2187714 , 0.13884006],
       [0.08369634, 0.14371844, 0.10205045, 0.06141395, 0.16047187,
        0.06711215, 0.11183473, 0.06987137, 0.11096761, 0.08886304]],
      dtype=float32)>