<a href="https://colab.research.google.com/github/SantosCristiano/artificial-intelligence-python/blob/main/Modelo_Linear_Simples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow 1

## Aula 12 - Tensor Flow - Redes Neurais - Modelo Linear Simples

### Importando o tensorflow e o numpy

In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np

Instructions for updating:
non-resource variables are not supported in the long term


### Função que define a semente aleatória do gerador de números pseudo-aleatórios NumPy.

In [ ]:
np.random.seed(97)

O <strong>tf.set_random_seed()</strong> define a semente no nível do gráfico, portanto, ele seleciona deterministicamente a semente para cada operação no gráfico.

In [ ]:
tf.set_random_seed(97)

## Criando pontos aleatórios

In [ ]:
rand_a = np.random.uniform(0, 100, (5, 5))
print(rand_a)

[[83.69441243 97.02358519 44.71537853 28.4581009  77.1216588 ]
 [29.89436322 97.63350749 92.91519751 20.46740657 34.51435172]
 [21.24000499 29.88601069 34.3650434  90.99622188 13.56417955]
 [19.48130578 16.08089137 11.21564326 41.51513221 30.13922734]
 [13.66098653 76.53951219 60.25384672 61.68587746 66.67817962]]


In [ ]:
rand_b = np.random.uniform(0, 100, (5, 1))
print(rand_b)

[[74.0853362 ]
 [40.57025945]
 [17.47357112]
 [17.24896835]
 [32.96277163]]


## Criando as variáveis <strong>a</strong> e <strong>b</strong>

In [ ]:
a = tf.placeholder(tf.float32)

In [ ]:
b = tf.placeholder(tf.float32)

## Operações de adição e de multiplicação

In [ ]:
add_op = a + b

In [ ]:
mult_op = a * b

## Criando a sessão que vai receber os dados no dicionário de feed, ou seja, de entrada

In [ ]:
with tf.Session() as sess:
  add_result = sess.run(add_op, feed_dict = {a: 10, b: 20})
  print(add_result)
  mult_result = sess.run(mult_op, feed_dict = {a: 10, b: 20})
  print(mult_result)

30.0
200.0


## Agora com os valores criados aleatoriamente e atribuídos a <strong>rand_a</strong> e <strong>rand_b</strong>

In [ ]:
with tf.Session() as sess:
  add_result = sess.run(add_op, feed_dict = {a: rand_a, b: rand_b})
  print("Adição:")
  print(add_result)
  print()
  print("Multiplicação:")
  mult_result = sess.run(mult_op, feed_dict = {a: rand_a, b: rand_b})
  print(mult_result)

Adição:
[[157.77975  171.10892  118.80071  102.543434 151.207   ]
 [ 70.46462  138.20377  133.48546   61.037666  75.08461 ]
 [ 38.713577  47.35958   51.838615 108.469795  31.03775 ]
 [ 36.730274  33.329857  28.464611  58.7641    47.388195]
 [ 46.62376  109.50229   93.21661   94.64865   99.640945]]

Multiplicação:
[[6200.5283  7188.0244  3312.7537  2108.328   5713.584  ]
 [1212.822   3961.0166  3769.5938   830.36804 1400.2561 ]
 [ 371.13876  522.21533  600.48004 1590.029    237.01466]
 [ 336.03244  277.37878  193.45827  716.0932   519.87054]
 [ 450.30402 2522.9546  1986.1338  2033.3375  2197.8975 ]]
