<a href="https://colab.research.google.com/github/SantosCristiano/artificial-intelligence-python/blob/main/tensorflow_syntax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow 1

## Sintaxe básica

### Importando o tensorflow

In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


### Verificando a versão

In [2]:
print(tf.__version__)

2.15.0


### Criando os tensores

In [3]:
codigo = tf.constant("Codigo ")
fluente = tf.constant("fluente")

### Verificando o tipo do objeto

In [4]:
type(codigo)

tensorflow.python.framework.ops.SymbolicTensor

### Imprimindo o objeto

In [5]:
print(codigo)

Tensor("Const:0", shape=(), dtype=string)


### Criando a sessão

In [6]:
with tf.Session() as sess:
  result = sess.run(codigo + fluente)


## Imprimindo o resultado

O 'b' minúsculo antes da string em python 3 representa bytes literais

In [7]:
print(result)

b'Codigo fluente'


## Soma utilizando tensores

In [8]:
a = tf.constant(10)

In [9]:
b = tf.constant(20)

In [10]:
type(a)

tensorflow.python.framework.ops.SymbolicTensor

## Note que ele controla o número de vezes que você faz a soma

In [11]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

### Mas, veja que a operação não foi feita, precisamos fazer isso dentro de uma sessão

In [12]:
with tf.Session() as sess:
  result = sess.run(a + b)

In [13]:
print(result)

30


## Matrizes

### Operações utilizando matrizes numpy, são as que mais são usadas no contexto do tensorflow e redes neurais.

In [14]:
const = tf.constant(10)

In [15]:
fill_mat = tf.fill((4, 4), 10)

In [16]:
my_zeros = tf.zeros((4, 4))

In [17]:
my_ones = tf.ones((4, 4))

In [18]:
my_rand_n = tf.random_normal((4, 4), mean = 0, stddev = 1.0)

In [19]:
my_rand_u = tf.random_uniform((4, 4), minval = 0, maxval = 1)

### Vamos criar uma lista e colocar todas as operações

In [20]:
my_ops = [const, fill_mat, my_zeros, my_ones, my_rand_n, my_rand_u]

## Vamos executar as operações em uma sessão interativa

In [21]:
sess = tf.InteractiveSession()

In [22]:
for op in my_ops:
  print(sess.run(op))
  print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 1.2445784  -0.2006684   0.32202736 -1.1333585 ]
 [ 0.34982347 -0.26325715  0.01344822  1.9393258 ]
 [ 1.6620952  -0.9416411   0.22854802 -0.9618834 ]
 [ 0.76516944 -1.3944314  -2.4972134  -0.09936805]]


[[0.7163851  0.55838907 0.7716688  0.23219216]
 [0.5668646  0.5271108  0.61409426 0.993652  ]
 [0.7932129  0.5806649  0.798916   0.72385466]
 [0.08120048 0.23630822 0.94833565 0.40618253]]




In [23]:
for op in my_ops:
  print(op.eval())
  print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.5844403  -1.4903532  -0.931694    0.11779968]
 [-0.29133257 -0.85813415  0.6474091   2.7424438 ]
 [-1.1400371  -0.1811644  -0.87401986 -0.91576093]
 [-1.2697098  -1.4368429   0.2676902  -0.42860824]]


[[0.7904556  0.17877722 0.34107542 0.420583  ]
 [0.2476995  0.8121004  0.6793475  0.23252702]
 [0.41363537 0.644909   0.33844888 0.13599741]
 [0.6187135  0.5988109  0.34478366 0.3039168 ]]




## Multiplicação de matrizes

In [24]:
a = tf.constant([
                 [1, 2],
                 [3, 4]
               ])

In [25]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [26]:
b = tf.constant([[10], [100]])

In [27]:
b.get_shape

<bound method Tensor.get_shape of <tf.Tensor 'Const_6:0' shape=(2, 1) dtype=int32>>

In [28]:
result = tf.matmul(a, b)

In [29]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

Posso fazer assim também:

In [30]:
result.eval()

array([[210],
       [430]], dtype=int32)